### ISSUE TITLE
Contradicting docs and code for test/prod environments

### ISSUE THREAD

**Issue by ZachDowd** [philipbrown/worldpay#2]
I'm trying to get payments working and ran into this from the docs and the code.

"If you send a WorldPay request in the production environment, your request body must include a testMode parameter of 100. In every other environment, this parameter must be set to 0."

```
if($this->env === 'production') return 0;
return 100;
```

**Comment by philipbrown** [comment]
Ah yeah, the docs are wrong. Thank you, I'll get that fixed :)

How are you finding the package?
