### ISSUE TITLE
GBP as currency code

### ISSUE THREAD

**Issue by ZachDowd** [philipbrown/worldpay#3]
I have just tried forking but having trouble with my GitHub/Bitbucket keys.

The currency code for GBP needs to be "GBP" and not "GB". Without it World Pay says..

"The currency or amount is not recognised."

**Comment by philipbrown** [comment]
Ah indeed. I'm sure at one point WorldPay had their own country codes.

Thanks Zach :)

**Comment by philipbrown** [comment]
Ah it's because I've used the countries list instead of the currency list. Nice one Zach, cheers!
