### ISSUE TITLE
Secret needs to be passed as an MD5 and not a string

### ISSUE THREAD

**Issue by ZachDowd** [philipbrown/worldpay#4]
Again, having trouble with my GitHub/BitBucket keys so I haven't been able to fork and clone the repo.

Can you update the docs to say that the secret needs to be passed as..

Secret::set(md5('my secret'));

Without this World Pay complains about an invalid installation ID.

**Comment by philipbrown** [comment]
Hmm, that can't be right, the signature is getting md5'd https://github.com/philipbrown/worldpay/blob/master/src/Request.php#L150

If that was the case WorldPay would complain about the signature not the installation id

**Comment by ZachDowd** [comment]
I checked through the code to see how the secret was being used. When I'm starting my request I'm using.. Secret::set(md5($secret)) .. which is then being MD5'ed once more when it's wrapped as the signature.

Without that it throws the error about the installation ID.

**Comment by philipbrown** [comment]
hmm, that's weird. I'll have to set up a WorldPay installation to see what's going on.

**Comment by philipbrown** [comment]
Hey Zach, I set up a WorldPay installation today and everything worked for me. Are you sure you've got the your signature set up correctly in the WorldPay dashboard?
