### ISSUE TITLE
Cant update composer after adding this to composer.json

### ISSUE THREAD

**Issue by astroanu** [philipbrown/worldpay#5]
"require": {
    "philipbrown/worldpay": "~2.0"
  }

i get this 

Updating dependencies (including require-dev)
    Authentication required (packagist.org): 
      Username:

**Comment by philipbrown** [comment]
Hmm, I guess it's just a composer problem, you don't need authentication for packagist.org

``` js
{
    "require": {
        "philipbrown/worldpay": "~2.0"
    }
}
```

`composer install`

This works fine for me ^^

I would update composer and try again.

Sorry!

**Comment by astroanu** [comment]
if i run composer install i get this 

Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

**Comment by philipbrown** [comment]
What happens when you run `composer update` ?

**Comment by astroanu** [comment]
I get the previous message : It asks for a username

Updating dependencies (including require-dev)
Authentication required (packagist.org): 
Username:
